version: '2'
services:
    flightlate-app:
        image: flightlate
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://flightlate-mysql:3306/flightlate?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    flightlate-mysql:
        extends:
            file: mysql.yml
            service: flightlate-mysql
